steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/pruebas-internas/microservices-demo/frontend:v0.2.1', './src/frontend/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/pruebas-internas/microservices-demo/frontend:v0.2.1']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['replace', '--force', '-f', './kubernetes-manifests/frontend-deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hipstershop-demo'